### ISSUE TITLE
The replay file cannot be imported normally

### ISSUE THREAD

**Issue by BaiGave** [Igrium/mc-world-export#42]
When I import the replay file with blender3.4.1, he has the following error：
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\import_vcap\import_replay_operator.py", line 103, in execute
    replay_file.load_replay(self.filepath, context, context.scene.collection, handle=handle, settings=settings)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\import_vcap\replay\replay_file.py", line 164, in load_replay
    materials[defname] = matlib.parse_raw(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\import_vcap\vcap\materials.py", line 82, in parse_raw
    node_tree.nodes.remove(node_tree.nodes.get('Principled BSDF')) # The generator adds this
TypeError: Nodes.remove(): error with argument 1, "node" -  Function.node does not support a 'None' assignment Node type

Minecraft version 1.19.2 ，Beta 0.6.3

**Comment by Sam54123** [comment]
Can you post the offending replay file?

**Comment by BaiGave** [comment]
I'm sorry I deleted it. After that, I used Blender 3.3 version, so there is no problem。
Maybe it may be a problem with the Blender version

**Comment by mcl0z** [comment]
i fixed it now it can use on blender 3.6+

**Comment by mcl0z** [comment]
it was worked very well
