### ISSUE TITLE
Error at import_vcap

### ISSUE THREAD

**Issue by Hashibutogarasu** [Igrium/mc-world-export#66]
If I load the `.replay` file blender 3.6 LTS throw the error.

StackTrace:

```
Python: Traceback (most recent call last):
  File "C:\Users\crow\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\import_vcap\import_replay_operator.py", line 103, in execute
    replay_file.load_replay(self.filepath, context, context.scene.collection, handle=handle, settings=settings)
  File "C:\Users\crow\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\import_vcap\replay\replay_file.py", line 139, in load_replay
    vcap_importer.load(world_file,
  File "C:\Users\crow\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\import_vcap\vcap\vcap_importer.py", line 60, in load
    mat = materials.parse(obj, os.path.basename(mat_id), vcontext)
  File "C:\Users\crow\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\import_vcap\vcap\materials.py", line 109, in parse
    node_tree.nodes.remove(node_tree.nodes.get('Principled BSDF'))
TypeError: Nodes.remove(): error with argument 1, "node" -  Function.node does not support a 'None' assignment Node type
```

Blender version: 3.6 LTS
Minecraft: 1.19.3
Fabric Loader: fabric-0.14.21
Mod version: 0.8.0
import_vcap: 0.7.0
OS: Windows11
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
GPU:NVIDIA GeForce RTX 3050 Ti Laptop GPU
Geforce Gameready Driver version: 31.0.15.3640

**Comment by Sam54123** [comment]
Right now, Blender 3.6 isn't supported due to a hiatus on my part and an
impending integration with MCPrep. Try using a previous version and then
upgrading.

**Comment by cinimaticc** [comment]
![image](https://github.com/Igrium/mc-world-export/assets/161723157/4d0b731c-b86b-41e4-97a9-ca9440ec8fd9)
i have moved to an old version and i use version 0.8 of this mod and it still does not work
