### ISSUE TITLE
Error installing import_vcap into blender

### ISSUE THREAD

**Issue by worldwidepixel** [Igrium/mc-world-export#67]
If I try to install the blender addon into _any*_ version of blender (*of those I tested [2.91.2, 2.79b, 3.0.0] ), I get the error below:

Error shown when attempting to install:

```Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\import_vcap\__init__.py", line 25, in <module>
    from . import operators, import_replay_operator, data
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\import_vcap\operators.py", line 3, in <module>
    from .vcap.context import VCAPSettings
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\import_vcap\vcap\context.py", line 7, in <module>
    class VCAPContext:
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\import_vcap\vcap\context.py", line 24, in VCAPContext
    materials: dict[str, Material] = {}
TypeError: 'type' object is not subscriptable
```
**EDIT: New day, new, and different (for some reason) error!**
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_vcap\__init__.py", line 25, in <module>
    from . import operators, import_replay_operator, data
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_vcap\operators.py", line 5, in <module>
    from .vcap import vcap_importer, import_obj
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_vcap\vcap\vcap_importer.py", line 20, in <module>
    from . import import_mesh, materials, util
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_vcap\vcap\import_mesh.py", line 6, in <module>
    from . import import_obj, materials
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_vcap\vcap\materials.py", line 166, in <module>
    def generate_nodes(obj, node_tree: NodeTree, image_provider: Callable[[str, bool], Image | None], name: str = 'vcap_mat', uv_input: NodeSocket = None):
TypeError: unsupported operand type(s) for |: 'bpy_struct_meta_idprop' and 'NoneType'
```

import-vcap version: 0.7.0
OS: Windows 10
CPU:  Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
GPU: NVIDIA GeForce GTX 1650 Ti

**P.S. I don't use GitHub that often, and I have never submitted an error. Sorry if I've made a fool of myself!**

**Comment by worldwidepixel** [comment]
**My blender version was too old. That is all.**

_I did make a fool of myself!_
