### ISSUE TITLE
[Crash on Startup] Mixin Transformation Failure with 'worldexport' mod and 'replaymod' during 'preLaunch' Entrypoint Stage

### ISSUE THREAD

**Issue by Destino233** [Igrium/mc-world-export#75]
# [Crash on Startup] Mixin Transformation Failure with 'worldexport' mod and 'replaymod' during 'preLaunch' Entrypoint Stage

## Description:
I'm encountering a crash when launching Minecraft using Fabric Loader, involving the 'replaymod' and 'worldexport' mods. The game fails to start due to an error in the mixin transformation process, specifically related to the 'ClientWorldMixin' from the 'worldexport' mod.

### Error Log Snippet:
\
 (A mod crashed on startup!)
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'replaymod'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'replaymod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'replaymod'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.replaymod.core.DummyChainLoadEntryPoint failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [worldexport.mixins.json:ClientWorldMixin from mod worldexport] from phase [DEFAULT] in config [worldexport.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'org.scaffoldeditor.worldexport.mixins.ClientWorldMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 20 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'org.scaffoldeditor.worldexport.mixins.ClientWorldMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858)
	... 23 more
\
### Steps to Reproduce:
1. Installed both 'replaymod' and 'worldexport' mods along with the latest compatible Fabric Loader and Fabric API for Minecraft version `1.20.1`.
2. Attempted to launch the game; it crashed during the startup phase while executing the 'preLaunch' entrypoint provided by 'replaymod'.
### Environment:
- Minecraft Version: `1.20.1`
- Fabric Loader Version: `0.15.7`
- Fabric API Version: `0.92.0+1.20.1`
- ReplayMod Version: `1.20.1-2.6.13`
- WorldExport Mod Version: `0.9.0`
### Expected Behavior:
The game should launch successfully with both mods functioning properly.
### Additional Information:
I've tried reinstalling both mods and confirmed they are up-to-date, however, the problem remains. There may be a compatibility issue or conflict between these two mods or other installed mods.

Would appreciate any assistance in resolving this issue or identifying if there's a known conflict that needs addressing.

Thank you!

**Comment by Igrium** [comment]
Can you post the entire game log?

**Comment by Destino233** [comment]
[minecraft-exported-crash-info-2024-02-15T22-28-35.zip](https://github.com/Igrium/mc-world-export/files/14304631/minecraft-exported-crash-info-2024-02-15T22-28-35.zip)

**Comment by SuperS0n1k** [comment]
I get the same error as well.
