### ISSUE TITLE
Unable to enable addon v0.9.1 in Blender 4.1

### ISSUE THREAD

**Issue by slbakkbone** [Igrium/mc-world-export#83]
![image](https://github.com/Igrium/mc-world-export/assets/57392880/473759f3-aa8f-4509-aad8-bd6a711bf754)
Stacktrace provided above appears and addon does not enable

**Comment by lynx-xdg** [comment]
I'm experiencing the same issue, with a clean 4.1 install of blender, and version 0.9.1 of the plugin

**Comment by lynx-xdg** [comment]
It seems the `NodeSocketInterfaceFloat` has been replaced by multiple functions for example the class to use would be `NodeSocketFloatTime` (https://docs.blender.org/api/current/bpy.types.NodeSocketFloatTime.html) I believe

**Comment by MACH2Simulations** [comment]
Have the same issue. 
Installed 4.0 For testing and the same thing happened. 

**Works on 3.6.8 if you install older version of Blender** 



Error log as text for readability 
```text
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import_vcap\__init__.py", line 25, in <module>
    from . import operators, import_replay_operator, data
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import_vcap\operators.py", line 5, in <module>
    from .vcap import vcap_importer, import_obj
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import_vcap\vcap\vcap_importer.py", line 20, in <module>
    from . import import_mesh, materials, util
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import_vcap\vcap\import_mesh.py", line 6, in <module>
    from . import import_obj, materials
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import_vcap\vcap\materials.py", line 11, in <module>
    from . import node_groups
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\import_vcap\vcap\node_groups.py", line 6, in <module>
    from bpy.types import NodeSocketInterfaceFloat, NodeSocketInterfaceVector, ShaderNodeMath
ImportError: cannot import name 'NodeSocketInterfaceFloat' from 'bpy.types' (unknown location)
```

**Comment by IvvyDevMC** [comment]
According to the _init_.py file, the only supported version is 3.6.0, so I wouldn't deviate far from that because it may very well not work.
