### ISSUE TITLE
The replay file cannot be imported

### ISSUE THREAD

**Issue by TOMsuppn** [Igrium/mc-world-export#84]
Python: Traceback (most recent call last):
  File "C:\Users\TOM\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\import_vcap\import_replay_operator.py", line 103, in execute
    replay_file.load_replay(self.filepath, context, context.scene.collection, handle=handle, settings=settings)
  File "C:\Users\TOM\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\import_vcap\replay\replay_file.py", line 139, in load_replay
    vcap_importer.load(world_file,
  File "C:\Users\TOM\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\import_vcap\vcap\vcap_importer.py", line 60, in load
    mat = materials.parse(obj, os.path.basename(mat_id), vcontext)
  File "C:\Users\TOM\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\import_vcap\vcap\materials.py", line 109, in parse
    node_tree.nodes.remove(node_tree.nodes.get('Principled BSDF'))
TypeError: Nodes.remove(): error with argument 1, "node" -  Function.node does not support a 'None' assignment Node type
I also tried blender 3.5 3.6 4.1, Minecraft 1.20.4 1.19.3, this plugin 0.8 0.9.1
They all have the same errors and problems

**Comment by XSXSXS2024** [comment]
Hello friend, I've also encountered the same problem. Have you managed to solve it?
<img width="629" alt="微信图片_20241102233504" src="https://github.com/user-attachments/assets/6772af1e-0a18-40e0-9f8a-39f96c213511">
